server.port=8081
spring.application.name=roulette-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://roulette-db:5432/roulette_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:casino}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:casino}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

banking.service.base-url=${BANKING_SERVICE_URL:http://localhost:8080}
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true