server.port=8080
banking.self.url=http://localhost:8080
spring.application.name=banking-service

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db
spring.datasource.username=casino
spring.datasource.password=casino
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true